apiVersion: v1
kind: Template
metadata:
  name: first-python-template
label:
  app: ${APPLICATION_NAME}
  createdBy: Joeychu-template-python
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    creationTimestamp:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: 
  spec:
    source:
      type: Git
      git:
        ref: ${GIT_REF}
        uri: ${GIT_URL}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'python:3.6'
          namespace: openshift
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    triggers:
      - imageChange:
          lastTriggeredImageID:
        type: ImageChange
      - generic:
          secret: secret
        type: Generic
      - github:
          secret: secret
        type: GitHub
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          env:
          - name: TZ
            value: Asia/Taipei
          ports:
          - containerPort: ${{SERVICE_PORT}}
            protocol: TCP
          resources: {}
        restartPolicy: Always
        dnsPolicy: ClusterFirst
        terminationGracePeriodSeconds: 30
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: ${SERVICE_PORT}-tcp
      port: ${{SERVICE_PORT}}
      protocol: TCP
      targetPort: ${{SERVICE_PORT}}
    selector:
      deploymentconfig: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
    creationTimestamp:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    host: ${HOSTNAME_HTTP}
    port:
      targetPort: ${SERVICE_PORT}-tcp
    to:
      kind: Service
      name: ${APPLICATION_NAME}
      weight: 100
    wildcardPolicy: None
parameters:
- displayName: Application Name
  value: first-python
  name: APPLICATION_NAME
  required: true
- displayName: Service Port
  value: "8081"
  name: SERVICE_PORT
- displayName: Git Url
  value: "https://github.com/joeyghb/Openshift-python-template-master.git"
  name: GIT_URL
- displayName: Git branch/tag ref
  value: "DEV"
  name: GIT_REF
- description: Custom hostname for http service route.
  displayName: Custom http Route Hostname                                            
  name: HOSTNAME_HTTP
  value: first-python-pytnon.192.168.99.100.nip.io
